sudo: required
services:
  - docker

before_install:
  - docker build -t riem-delhi/docker-react -f Dockerfile.dev .

script:
  - docker run riem-delhi/docker-react npm run test -- --coverage

git:
  depth: 25
  quiet: true
